name: todo_win
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_mobx: ^2.0.5
  flutter_slidable: ^1.2.0
  get_it: ^7.2.0
  intl: ^0.17.0
  mobx: ^2.0.4
  path: ^1.8.1
  sqflite: ^2.0.2+1

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^4.1.3
  mobx_codegen: ^2.0.1+3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

